services:
    caddy:
        profiles: [development]
        ports:
            - '127.0.0.1:8080:8080'

    laravel.test:
        profiles: [development]

    mysql:
        profiles: [development]
        ports:
            - '127.0.0.1:${FORWARD_DB_PORT:-3306}:3306'

    redis:
        profiles: [development]
        ports:
            - '127.0.0.1:${FORWARD_REDIS_PORT:-6379}:6379'

    adminer:
        profiles: [development]
        ports:
            - '127.0.0.1:${ADMINER_PORT:-8081}:8080'
